version: '3'

services:
  api:
    build: ./api
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    container_name: blog-api

  client:
    build: ./client
    restart: always
    environment:
      PORT: '80'
    ports:
      - '80:80'
    container_name: blog-client

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'password'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    container_name: blog-db
volumes:
  pgdata:
